name: Cloud PC test auto

on:
  workflow_dispatch:
  
jobs:
  test-cloud-pc-auto:
    runs-on: windows-latest
    timeout-minutes: 420

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Win RDP Enabler
        uses: Veniamin668/win-rdp-enabler@main
        env:
         TAIL_KEY: ${{ secrets.TAIL_KEY }}
         ADMIN_PASS: ${{ secrets.ADMIN_PASS }}
         USE_CUSTOM_USER: 'true'
         CUSTOM_USERNAME: 'ktoya'
         CUSTOM_PASSWORD: ${{ secrets.CUSTOM_PASSWORD }}

      - name: Purge Windows Bloat
        uses: Veniamin668/windows-debloater-runner@v1
        with:
          enable: 'true'
          
      - name: 4. wait session (7 hours)
        run: |
          Write-Host "Cloud PC запущен и ждет тебя в сети! Не закрывай этот воркфлоу."
          while ($true) {
              Start-Sleep -Seconds 60
          }
        shell: pwsh
